const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function generatePdfReport(scan) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const reportsDir = path.join(__dirname, '..', 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      const fileName = `${scan._id}.pdf`;
      const filePath = path.join(reportsDir, fileName);
      const writeStream = fs.createWriteStream(filePath);
      doc.pipe(writeStream);

      doc.fontSize(24).font('Helvetica-Bold').text('SUPPLY CHAIN VULNERABILITY REPORT', { align: 'center' });
      doc.moveDown();
      doc.fontSize(14).font('Helvetica').text('Generated by VulnMap', { align: 'center' });
      doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.text(`Stack Name: ${scan.stackName}`, { align: 'center' });
      doc.moveDown(3);

      doc.fontSize(18).font('Helvetica-Bold').text('Executive Summary');
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica').text(scan.aiSummary || 'No summary available.', { align: 'justify' });
      doc.moveDown(2);

      doc.fontSize(18).font('Helvetica-Bold').text('Risk Overview');
      doc.moveDown(0.5);
      doc.fontSize(14).font('Helvetica').text(`Overall Risk Score: ${scan.overallRiskScore}/100`);
      doc.moveDown(2);

      doc.fontSize(18).font('Helvetica-Bold').text('Critical Nodes Priority');
      doc.moveDown(0.5);
      
      const sortedNodes = [...scan.nodes].sort((a, b) => b.riskScore - a.riskScore);
      let count = 1;
      
      sortedNodes.forEach(node => {
        if (count > 5) return;
        doc.fontSize(12).font('Helvetica-Bold').text(`${count}. ${node.id} (v${node.version}) - Risk Score: ${node.riskScore}`);
        doc.font('Helvetica').text(`Trust Depth: ${node.trustDepth} | Type: ${node.type}`);
        if (node.cves && node.cves.length > 0) {
            const topCve = node.cves[0];
            doc.text(`Top CVE: ${topCve.cveId} - ${topCve.severity}`);
        } else {
            doc.text('Top CVE: None found');
        }
        doc.moveDown(0.5);
        count++;
      });

      doc.moveDown(2);

      doc.fontSize(10).font('Helvetica').text('VulnMap — vulnmap.vercel.app', 50, doc.page.height - 50, { align: 'center' });

      doc.end();
      writeStream.on('finish', () => {
        resolve(`/reports/${fileName}`);
      });
      writeStream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePdfReport };
